apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.details.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: {{ .Release.Name }}